---
title: "Onboarding to GitHub and RStudio"
description: |
  Tools and practices to hit the ground running
author:
  - name: Mauro Lepore
    url: https://github.com/maurolepore
date: "2020-06-23"
output: 
  distill::distill_article:
  toc: true
  toc_depth: 3
  self_contained: true
categories:
  - other
  - community
preview: preview.jpg
twitter:
  site: "@mauro_lepore"
  creator: "@mauro_lepore"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>"
)
```

At 2DII we use a particular workflow -- a set of tools and practices. This post is about what you should know to work effectively with us, or whoever uses the same workflow.

### Introduction to GitHub

We collaborate on GitHub, and embrace the so called [GitHub flow](https://guides.github.com/introduction/flow/). Whatever your experience with GitHub, you may like these resources:

* [What is GitHub?](https://youtu.be/w3jLJU7DT5E) (4' video).
* [Introduction to GitHub](https://lab.github.com/githubtraining/introduction-to-github) (1-2 h tutorial from [GitHub Lab](https://youtu.be/9S0p8YMQzsM)).

### Join 2DII's GitHub organization

> [GitHub] Organizations are shared accounts where businesses and open-source projects can collaborate across many projects at once. Owners and administrators can manage member access to the organization's data and projects with sophisticated security and administrative features. -- [About organizations](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-organizations)

To join [our GitHub organization](https://github.com/2DegreesInvesting) you need to be invited by someone with special ("Owner") privileges. Find that person by asking on the `#coding` channel on 2DII's Slack and share your GitHub username.

### Setup

Most of our code on GitHub is written in R and from RStudio. Here is how to set things up:

* Setup ([instructions](https://happygitwithr.com/workshops.html); [20' video](https://youtu.be/YDsoKUVsJls)). If you are already set, use this guide to confirm we are all set in the same way.

* [How to contribute to GitHub from the terminal and from RStudio](https://youtu.be/y8lOGz1yAj4) (35' video)^[Caveat: In this video I violate the GitHub flow in that I submit a pull request not from a `feature` branch (as I should) but from the `master` branch.].

### Why Git, and how it relates to GitHub and RStudio

Git is the heart of GitHub. We use it to track each meaningful change in our projects. You may use Git from the terminal or from a dedicated program (e.g. [GitKraken](https://www.gitkraken.com/)); but you rarely need anything special because the most useful features of Git are available directly from RStudio. 

* [Git handbook](https://guides.github.com/introduction/git-handbook/#version-control) (10' read).
* [Git cheat sheets](https://github.github.com/training-kit/).
* [Collaboration and time travel- version control with git, github and RStudio](https://rstudio.com/resources/webinars/collaboration-and-time-travel-version-control-with-git-github-and-rstudio/) (50' video).

### Next

We are working on multiple projects you may want to know about:

* [ds-incubator](https://github.com/2DegreesInvesting/ds-incubator): Weekly meetups to share best practices.
* [resources](https://2degreesinvesting.github.io/resources/): A place to explore and share resources.
* [coding-helpdesk](https://2degreesinvesting.github.io/coding-helpdesk): Live support by appointment.
* [r2dii](https://2degreesinvesting.github.io/r2dii/index.html): A collection of R packages we maintain.

----

What else (or less) do you think a successful onboarding should have?