---
title: "GitHub flow"
description: |
  Submit pull requests from any branch -- except master
date: 07-25-2020
author:
  - name: Mauro Lepore
    url: https://github.com/maurolepore
base_url: https://2degreesinvesting.github.io/
output: 
  distill::distill_article:
    toc: true
    self_contained: true
categories:
  - other
  - community
preview: preview.jpg
twitter:
  site: "@mauro_lepore"
  creator: "@mauro_lepore"
---

If your team uses the [GitHub flow](https://guides.github.com/introduction/flow/), you should [submit your pull requests from any branch -- except master](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/). The reasons are not immediately obvious. This post explains why violating the GitHub flow sometimes gives you no trouble, while other times it leaves you a mess.

Say you want to contribute to a project -- let's call it _upstream_. You don't own _upstream_, so you can't push commits to  _upstream/master_, the branch _master_ of the project _upstream_. That's okay: you can still submit a pull request from your fork of _upstream_ -- let's call it _origin_. 

As you do own _origin_, can you push commits to _origin/master_ then submit a pull request into _upstream/master_? Yes, you "can"; but that is a bad idea. 

Consider this example. After you forked _upstream_, you add two commits to _origin/master_ and submit your first pull request into _upstream/master_. This goes smoothly.

But soon the history of _origin_ and _upstream_ start to diverge -- and you may not even notice. The maintainer squashed your two commits into a new, single commit that tells the story of your pull request more succinctly. The Git history of both repos -- _origin_ and _upstream_ -- is already different. And it gets worse: Other people's pull-requests are also merged into _upstream/master_, and it now has changes that your _origin/master_ lacks.

Your second pull request exposes the problem. You add a new commit to _origin/master_ and submit another pull request into _upstream/master_. Now you've got a mess: Although they had been merged, the commits you submitted before still show up in this second pull request; and the commits you lack cause merge conflicts with your new commits on this pull request.

Avoid the mess. Just remember to [submit your pull requests from any branch -- except master](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/). For R users it gets better: the [pull-request helpers from the usethis package](https://usethis.r-lib.org/reference/pull-requests.html) implement the  [GitHub flow](https://guides.github.com/introduction/flow/) automatically. Too often to "just remember" doesn't work. Instead it's best to use systems that automatically enforce the behaviour you want to display. Why not automate repetitive tasks like pull requests?
